/**
 * tc-project-service
 * Services that provide access and interaction with user projects.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TcProjectService) {
      root.TcProjectService = {};
    }
    root.TcProjectService.BillingAccount = factory(root.TcProjectService.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BillingAccount model module.
   * @module model/BillingAccount
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>BillingAccount</code>.
   * @alias module:model/BillingAccount
   * @class
   * @param billingAccountName {String} 
   */
  var exports = function(billingAccountName) {
    var _this = this;

    _this['billingAccountName'] = billingAccountName;
  };

  /**
   * Constructs a <code>BillingAccount</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BillingAccount} obj Optional instance to populate.
   * @return {module:model/BillingAccount} The populated <code>BillingAccount</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('billingAccountName')) {
        obj['billingAccountName'] = ApiClient.convertToType(data['billingAccountName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} billingAccountName
   */
  exports.prototype['billingAccountName'] = undefined;



  return exports;
}));


