/**
 * tc-project-service
 * Services that provide access and interaction with user projects.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProjectQuestion'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ProjectQuestion'));
  } else {
    // Browser globals (root is window)
    if (!root.TcProjectService) {
      root.TcProjectService = {};
    }
    root.TcProjectService.DirectProjectType = factory(root.TcProjectService.ApiClient, root.TcProjectService.ProjectQuestion);
  }
}(this, function(ApiClient, ProjectQuestion) {
  'use strict';




  /**
   * The DirectProjectType model module.
   * @module model/DirectProjectType
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DirectProjectType</code>.
   * @alias module:model/DirectProjectType
   * @class
   * @param id {Number} 
   * @param name {String} 
   */
  var exports = function(id, name) {
    var _this = this;

    _this['id'] = id;
    _this['name'] = name;

  };

  /**
   * Constructs a <code>DirectProjectType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DirectProjectType} obj Optional instance to populate.
   * @return {module:model/DirectProjectType} The populated <code>DirectProjectType</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('projectQuestions')) {
        obj['projectQuestions'] = ApiClient.convertToType(data['projectQuestions'], [ProjectQuestion]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Array.<module:model/ProjectQuestion>} projectQuestions
   */
  exports.prototype['projectQuestions'] = undefined;



  return exports;
}));


