/**
 * tc-project-service
 * Services that provide access and interaction with user projects.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Permission'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Permission'));
  } else {
    // Browser globals (root is window)
    if (!root.TcProjectService) {
      root.TcProjectService = {};
    }
    root.TcProjectService.PermissionsBody = factory(root.TcProjectService.ApiClient, root.TcProjectService.Permission);
  }
}(this, function(ApiClient, Permission) {
  'use strict';




  /**
   * The PermissionsBody model module.
   * @module model/PermissionsBody
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PermissionsBody</code>.
   * @alias module:model/PermissionsBody
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PermissionsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PermissionsBody} obj Optional instance to populate.
   * @return {module:model/PermissionsBody} The populated <code>PermissionsBody</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('permissions')) {
        obj['permissions'] = ApiClient.convertToType(data['permissions'], [Permission]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Permission>} permissions
   */
  exports.prototype['permissions'] = undefined;



  return exports;
}));


