/**
 * tc-project-service
 * Services that provide access and interaction with user projects.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TcProjectService) {
      root.TcProjectService = {};
    }
    root.TcProjectService.PermissionInfo = factory(root.TcProjectService.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PermissionInfo model module.
   * @module model/PermissionInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PermissionInfo</code>.
   * @alias module:model/PermissionInfo
   * @class
   * @param reportPermissionNumber {Number} 
   * @param readPermissionNumber {Number} 
   * @param writePermissionNumber {Number} 
   * @param fullPermissionNumber {Number} 
   * @param totalPermissionNumber {Number} 
   */
  var exports = function(reportPermissionNumber, readPermissionNumber, writePermissionNumber, fullPermissionNumber, totalPermissionNumber) {
    var _this = this;

    _this['reportPermissionNumber'] = reportPermissionNumber;
    _this['readPermissionNumber'] = readPermissionNumber;
    _this['writePermissionNumber'] = writePermissionNumber;
    _this['fullPermissionNumber'] = fullPermissionNumber;
    _this['totalPermissionNumber'] = totalPermissionNumber;
  };

  /**
   * Constructs a <code>PermissionInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PermissionInfo} obj Optional instance to populate.
   * @return {module:model/PermissionInfo} The populated <code>PermissionInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('reportPermissionNumber')) {
        obj['reportPermissionNumber'] = ApiClient.convertToType(data['reportPermissionNumber'], 'Number');
      }
      if (data.hasOwnProperty('readPermissionNumber')) {
        obj['readPermissionNumber'] = ApiClient.convertToType(data['readPermissionNumber'], 'Number');
      }
      if (data.hasOwnProperty('writePermissionNumber')) {
        obj['writePermissionNumber'] = ApiClient.convertToType(data['writePermissionNumber'], 'Number');
      }
      if (data.hasOwnProperty('fullPermissionNumber')) {
        obj['fullPermissionNumber'] = ApiClient.convertToType(data['fullPermissionNumber'], 'Number');
      }
      if (data.hasOwnProperty('totalPermissionNumber')) {
        obj['totalPermissionNumber'] = ApiClient.convertToType(data['totalPermissionNumber'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} reportPermissionNumber
   */
  exports.prototype['reportPermissionNumber'] = undefined;
  /**
   * @member {Number} readPermissionNumber
   */
  exports.prototype['readPermissionNumber'] = undefined;
  /**
   * @member {Number} writePermissionNumber
   */
  exports.prototype['writePermissionNumber'] = undefined;
  /**
   * @member {Number} fullPermissionNumber
   */
  exports.prototype['fullPermissionNumber'] = undefined;
  /**
   * @member {Number} totalPermissionNumber
   */
  exports.prototype['totalPermissionNumber'] = undefined;



  return exports;
}));


