/**
 * tc-project-service
 * Services that provide access and interaction with user projects.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TcProjectService) {
      root.TcProjectService = {};
    }
    root.TcProjectService.ProjectQuestionOption = factory(root.TcProjectService.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ProjectQuestionOption model module.
   * @module model/ProjectQuestionOption
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ProjectQuestionOption</code>.
   * @alias module:model/ProjectQuestionOption
   * @class
   * @param id {Number} 
   */
  var exports = function(id) {
    var _this = this;

    _this['id'] = id;





  };

  /**
   * Constructs a <code>ProjectQuestionOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectQuestionOption} obj Optional instance to populate.
   * @return {module:model/ProjectQuestionOption} The populated <code>ProjectQuestionOption</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('questionOptionText')) {
        obj['questionOptionText'] = ApiClient.convertToType(data['questionOptionText'], 'String');
      }
      if (data.hasOwnProperty('projectQuestion')) {
        obj['projectQuestion'] = ApiClient.convertToType(data['projectQuestion'], 'String');
      }
      if (data.hasOwnProperty('answerHtmlId')) {
        obj['answerHtmlId'] = ApiClient.convertToType(data['answerHtmlId'], 'String');
      }
      if (data.hasOwnProperty('hasAssociatedTextbox')) {
        obj['hasAssociatedTextbox'] = ApiClient.convertToType(data['hasAssociatedTextbox'], 'Boolean');
      }
      if (data.hasOwnProperty('associatedTextboxHtmlId')) {
        obj['associatedTextboxHtmlId'] = ApiClient.convertToType(data['associatedTextboxHtmlId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} questionOptionText
   */
  exports.prototype['questionOptionText'] = undefined;
  /**
   * @member {String} projectQuestion
   */
  exports.prototype['projectQuestion'] = undefined;
  /**
   * @member {String} answerHtmlId
   */
  exports.prototype['answerHtmlId'] = undefined;
  /**
   * @member {Boolean} hasAssociatedTextbox
   */
  exports.prototype['hasAssociatedTextbox'] = undefined;
  /**
   * @member {String} associatedTextboxHtmlId
   */
  exports.prototype['associatedTextboxHtmlId'] = undefined;



  return exports;
}));


