/**
 * tc-project-service
 * Services that provide access and interaction with user projects.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TcProjectService) {
      root.TcProjectService = {};
    }
    root.TcProjectService.UserProjectContent = factory(root.TcProjectService.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UserProjectContent model module.
   * @module model/UserProjectContent
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>UserProjectContent</code>.
   * @alias module:model/UserProjectContent
   * @class
   * @param id {Number} 
   * @param name {String} 
   * @param customerId {Number} 
   * @param customerName {String} 
   */
  var exports = function(id, name, customerId, customerName) {
    var _this = this;

    _this['id'] = id;
    _this['name'] = name;
    _this['customerId'] = customerId;
    _this['customerName'] = customerName;

  };

  /**
   * Constructs a <code>UserProjectContent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserProjectContent} obj Optional instance to populate.
   * @return {module:model/UserProjectContent} The populated <code>UserProjectContent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('customerId')) {
        obj['customerId'] = ApiClient.convertToType(data['customerId'], 'Number');
      }
      if (data.hasOwnProperty('customerName')) {
        obj['customerName'] = ApiClient.convertToType(data['customerName'], 'String');
      }
      if (data.hasOwnProperty('projectForumCategoryId')) {
        obj['projectForumCategoryId'] = ApiClient.convertToType(data['projectForumCategoryId'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} customerId
   */
  exports.prototype['customerId'] = undefined;
  /**
   * @member {String} customerName
   */
  exports.prototype['customerName'] = undefined;
  /**
   * @member {Number} projectForumCategoryId
   */
  exports.prototype['projectForumCategoryId'] = undefined;



  return exports;
}));


