/**
 * tc-project-service
 * Services that provide access and interaction with user projects.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TcProjectService);
  }
}(this, function(expect, TcProjectService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TcProjectService.PermissionInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PermissionInfo', function() {
    it('should create an instance of PermissionInfo', function() {
      // uncomment below and update the code to test PermissionInfo
      //var instane = new TcProjectService.PermissionInfo();
      //expect(instance).to.be.a(TcProjectService.PermissionInfo);
    });

    it('should have the property reportPermissionNumber (base name: "reportPermissionNumber")', function() {
      // uncomment below and update the code to test the property reportPermissionNumber
      //var instane = new TcProjectService.PermissionInfo();
      //expect(instance).to.be();
    });

    it('should have the property readPermissionNumber (base name: "readPermissionNumber")', function() {
      // uncomment below and update the code to test the property readPermissionNumber
      //var instane = new TcProjectService.PermissionInfo();
      //expect(instance).to.be();
    });

    it('should have the property writePermissionNumber (base name: "writePermissionNumber")', function() {
      // uncomment below and update the code to test the property writePermissionNumber
      //var instane = new TcProjectService.PermissionInfo();
      //expect(instance).to.be();
    });

    it('should have the property fullPermissionNumber (base name: "fullPermissionNumber")', function() {
      // uncomment below and update the code to test the property fullPermissionNumber
      //var instane = new TcProjectService.PermissionInfo();
      //expect(instance).to.be();
    });

    it('should have the property totalPermissionNumber (base name: "totalPermissionNumber")', function() {
      // uncomment below and update the code to test the property totalPermissionNumber
      //var instane = new TcProjectService.PermissionInfo();
      //expect(instance).to.be();
    });

  });

}));
