/**
 * tc-project-service
 * Services that provide access and interaction with user projects.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TcProjectService);
  }
}(this, function(expect, TcProjectService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TcProjectService.ProjectPermissionsGetResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectPermissionsGetResponse', function() {
    it('should create an instance of ProjectPermissionsGetResponse', function() {
      // uncomment below and update the code to test ProjectPermissionsGetResponse
      //var instane = new TcProjectService.ProjectPermissionsGetResponse();
      //expect(instance).to.be.a(TcProjectService.ProjectPermissionsGetResponse);
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new TcProjectService.ProjectPermissionsGetResponse();
      //expect(instance).to.be();
    });

    it('should have the property permissionType (base name: "permissionType")', function() {
      // uncomment below and update the code to test the property permissionType
      //var instane = new TcProjectService.ProjectPermissionsGetResponse();
      //expect(instance).to.be();
    });

  });

}));
