/**
 * tc-project-service
 * Services that provide access and interaction with user projects.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TcProjectService);
  }
}(this, function(expect, TcProjectService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TcProjectService.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('directProjectsPost', function() {
      it('should call directProjectsPost successfully', function(done) {
        //uncomment below and update the code to test directProjectsPost
        //instance.directProjectsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('directProjectsProjectIdBillingaccountDelete', function() {
      it('should call directProjectsProjectIdBillingaccountDelete successfully', function(done) {
        //uncomment below and update the code to test directProjectsProjectIdBillingaccountDelete
        //instance.directProjectsProjectIdBillingaccountDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('directProjectsProjectIdBillingaccountPost', function() {
      it('should call directProjectsProjectIdBillingaccountPost successfully', function(done) {
        //uncomment below and update the code to test directProjectsProjectIdBillingaccountPost
        //instance.directProjectsProjectIdBillingaccountPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('directProjectsProjectIdCopilotDelete', function() {
      it('should call directProjectsProjectIdCopilotDelete successfully', function(done) {
        //uncomment below and update the code to test directProjectsProjectIdCopilotDelete
        //instance.directProjectsProjectIdCopilotDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('directProjectsProjectIdCopilotPost', function() {
      it('should call directProjectsProjectIdCopilotPost successfully', function(done) {
        //uncomment below and update the code to test directProjectsProjectIdCopilotPost
        //instance.directProjectsProjectIdCopilotPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('directProjectsProjectIdGet', function() {
      it('should call directProjectsProjectIdGet successfully', function(done) {
        //uncomment below and update the code to test directProjectsProjectIdGet
        //instance.directProjectsProjectIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('directProjectsProjectIdMilestonesPost', function() {
      it('should call directProjectsProjectIdMilestonesPost successfully', function(done) {
        //uncomment below and update the code to test directProjectsProjectIdMilestonesPost
        //instance.directProjectsProjectIdMilestonesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('directProjectsProjectIdPermissionsDelete', function() {
      it('should call directProjectsProjectIdPermissionsDelete successfully', function(done) {
        //uncomment below and update the code to test directProjectsProjectIdPermissionsDelete
        //instance.directProjectsProjectIdPermissionsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('directProjectsProjectIdPermissionsGet', function() {
      it('should call directProjectsProjectIdPermissionsGet successfully', function(done) {
        //uncomment below and update the code to test directProjectsProjectIdPermissionsGet
        //instance.directProjectsProjectIdPermissionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('directProjectsProjectIdPermissionsPost', function() {
      it('should call directProjectsProjectIdPermissionsPost successfully', function(done) {
        //uncomment below and update the code to test directProjectsProjectIdPermissionsPost
        //instance.directProjectsProjectIdPermissionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('directProjectsProjectIdPermissionsPut', function() {
      it('should call directProjectsProjectIdPermissionsPut successfully', function(done) {
        //uncomment below and update the code to test directProjectsProjectIdPermissionsPut
        //instance.directProjectsProjectIdPermissionsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('directProjectsUserGet', function() {
      it('should call directProjectsUserGet successfully', function(done) {
        //uncomment below and update the code to test directProjectsUserGet
        //instance.directProjectsUserGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
